### ISSUE TITLE
Diagnostics reporter standardrb does not exist

### ISSUE THREAD

**Issue by benortiz** [bekicot/solargraph-standardrb#6]
I'm having a difficult time figuring out why I'm getting the above error.

I've gem installed `standard`, `solargraph-standardrb`, and `solargraph`.

For context, I'm running Solargraph through Neovim using the built in LSP.

My `.solargraph.yml` looks like this:
```yaml
include:
- "**/*.rb"
exclude:
- spec/**/*
- test/**/*
- vendor/**/*
- ".bundle/**/*"
require: []
domains: []
plugins:
- solargraph-standardrb
reporters:
- standardrb
- require_not_found
max_files: 5000
```

I tried changing `standardrb` to `standard` since that's the name of the gem and no luck. Do you have any ideas on how to track down what's going on? Thanks!
